{{- if not .Values.existingSecret.name }}
{{- $current := lookup "v1" "Secret" .Release.Namespace (include "periscope.secretName" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "periscope.secretName" . }}
  labels:
    {{- include "periscope.labels" . | nindent 4 }}
type: Opaque
data:
  COOKIE_SECRET: {{ if $current }}{{ index $current.data "COOKIE_SECRET" | quote }}{{ else }}{{ default (randAlphaNum 64) .Values.cookieSecret | b64enc | quote }}{{ end }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret | b64enc | quote }}
{{- end }}
